name: Build OpenNavBar WinX edition

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenNavBar
        run: |
          git clone https://codeberg.org/ItsZariep/OpenNavBar.git opennavbar

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build debug APK
        working-directory: opennavbar
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OpenNavBar-WinX-debug
          path: opennavbar/app/build/outputs/apk/debug/*.apk
